### ISSUE TITLE
Make all core code pass JSHint

### ISSUE THREAD

**Issue by FilipNest** [CityWebConsultants/Iris#134]

**Comment by FilipNest** [comment]
JSHint header I'm using is:

```
/*jshint nomen: true, node:true */
/* globals iris,mongoose,Promise */
```

**Comment by adam-clarey** [comment]
Did this get pushed in?

**Comment by FilipNest** [comment]
My first one did (see "merged" above). Still more to do and I'm not sure how the testing side is going.

**Comment by FilipNest** [comment]
We're at the stage where we can turn JSHint on on the automatic tests.
