### ISSUE TITLE
Cannot re-order fields in entity

### ISSUE THREAD

**Issue by alexbor** [CityWebConsultants/Iris#140]
Can no longer re-order fields in an entity with click and drag

**Comment by FilipNest** [comment]
Also can't add a field.

**Comment by adam-clarey** [comment]
Re-ordering fixed here https://github.com/CityWebConsultants/Iris/pull/150

**Comment by adam-clarey** [comment]
'Add new field' issue fixed here https://github.com/CityWebConsultants/Iris/pull/145
