### ISSUE TITLE
Testing Prioritization

### ISSUE THREAD

**Issue by facascante** [CityWebConsultants/Iris#189]
Testing Prioritization
1. schema management -- ongoing please refer to issue #190 
2. entity management -- ongoing please refer to issue #192
3. forms with fieldset

NOTE : feel free to add content and change the number.

Testing

Overview
  Iris test is running on travis-ci, it uses jasmine, frisby, phantomjs and jasperjs.

Setup Iris fork repo to run test
1. go to https://travis-ci.org, login using your github account
2. Click Add new repositories then choose the repository you want to add toggling the the switch
   NOTE : make sure you have an admin access to repo you want to enable.
3. start pushing and your ready to go

Setup test on your local
1. install the following global command
   $> npm install -g grunt-cli jasmine-node pm2
2. clone the iris-project-template or you may setup your own site by following the iris wiki and add the package.json dev-dependencies to be found in iris-project-template
       $> git clone https://github.com/CityWebConsultants/iris-project-template.git
3. install all the package.json dependencies including dev
       $> npm install --only=dev
4. navigate to your test mongodb and import the following json file, you may ommit this import, by modifying the test_config.js available in the test folder to you current set of admin account
       $> mongoimport --db mysite --collection users --file fixtures/users.json
   $> mongoimport --db mysite --collection pages --file fixtures/pages.json
   5.to save on console, you may run the iris site in pm2 instance
       $> pm2 start index.js(or your site script file)
5. run the test
       $> grunt default

Known Issues
1. During PR the module being npm installed is the destination branch of which pr is to be merge. you should ignore it or remove test build for PR in the travis-ci repo setting :)

**Comment by FilipNest** [comment]
Added to a testing entry in the wiki.

https://github.com/CityWebConsultants/Iris/wiki/Testing
