### ISSUE TITLE
First time login when creating a site doesn't have a proper authPass

### ISSUE THREAD

**Issue by FilipNest** [CityWebConsultants/Iris#218]
Steps to reproduce:
- Start a new site with a fresh database.
- Run standard installation profile
- Create a page with path "/" or any path really.
- Visit the path.

Logs point to an authPass related bug that is failing in a hook that stops before it gets to the path module so the path doesn't update properly.

Logging out and back in fixes the issue.

**Comment by FilipNest** [comment]
This is due to the getAuthPass() function not existing in iris.auth.globals.userList[userid] in that one session. I'm sure it's an obvious fix somewhere in user.js but I can't find where yet.

**Comment by facascante** [comment]
Error when calling hook hook_entity_created from entity on line 52 of C:\Users\OEM_PC\Documents\work\project\cwc\fresh-site\node_modules\irisjs\modules\core\entity\entity_views.js iris.modules.auth.globals.userList[authUser].getAuthPass is not a function

**Comment by FilipNest** [comment]
Yeah, that's what I said above. It's not entity_views that's the problem. It's that the `iris.auth.globals.userList[userid]` is not set up properly that session. At least I think that's it.

**Comment by facascante** [comment]
copy
