### ISSUE TITLE
Bugs in admin UI since update

### ISSUE THREAD

**Issue by FilipNest** [CityWebConsultants/Iris#237]
Since https://github.com/CityWebConsultants/Iris/pull/231 the admin dashboard seems to be showing:

"Auto-generate tokenised url paths for entities." from the autopath module.

Also the restart button wasn't working for me on the restart page.

**Comment by adam-clarey** [comment]
These fixes have been pushed to this PR https://github.com/CityWebConsultants/Iris/pull/234 as that involves restarts triggered from the clientside
