### ISSUE TITLE
inconsistent treatment of paths at /admin/config/

### ISSUE THREAD

**Issue by pau1m** [CityWebConsultants/Iris#240]
Different page output at `admin/config/` and `admin/config` (without slash).

![Uploading Screen Shot 2016-05-13 at 11.31.23.png…]()
![Uploading Screen Shot 2016-05-13 at 11.31.30.png…]()

same applies to `admin/config/manage/` and `admin/config/manage`

**Comment by FilipNest** [comment]
We can probably put an Express handler that works out trailing slashes and redirects. What's better, trailing slash or none? How do other systems do this?

**Comment by adam-clarey** [comment]
I'd say without, but thats just preference

**Comment by adam-clarey** [comment]
can you take this one fil?
