### ISSUE TITLE
User List on first time login

### ISSUE THREAD

**Issue by pau1m** [CityWebConsultants/Iris#241]
On the user list page linked from `/admin/users` I get a 404 on first time use. 

After enabling Entity UI the page displays normally.

If a user can't use the page out of the box it shouldn't be linked to.

<img width="1440" alt="screen shot 2016-05-13 at 10 44 59" src="https://cloud.githubusercontent.com/assets/431223/15244237/0eea1eea-18f8-11e6-9c37-c45669e0f030.png">

**Comment by FilipNest** [comment]
That page should only work if entity_ui is enabled. The definition of that menu item should therefore be moved inside the entity_ui module so it only works if that's enabled. Unless we want to make entity_ui core and always enabled.

**Comment by adam-clarey** [comment]
fixed in https://github.com/CityWebConsultants/Iris/pull/253
