### ISSUE TITLE
Duplicate titles at /admin/config/content-authoring/textfilters/create

### ISSUE THREAD

**Issue by pau1m** [CityWebConsultants/Iris#242]
This page is linked from Config

Unable to Create anything.

<img width="1127" alt="screen shot 2016-05-13 at 11 06 32" src="https://cloud.githubusercontent.com/assets/431223/15244832/07cc0b98-18fb-11e6-8652-ee2d45cd2699.png">

On clicking submit, get:

<img width="1200" alt="screen shot 2016-05-13 at 11 09 08" src="https://cloud.githubusercontent.com/assets/431223/15244860/310b0bb2-18fb-11e6-939f-3867cef8c8c7.png">

From logs:

```
{"name":"iris","hostname":"Pau1ms-MacBook-Pro.local","pid":4024,"level":50,"msg":"Error when calling hook hook_form_render__textfilter from textfilters on line 231 of /Users/p/Documents/webs/in-house/iris-test1/node_modules/irisjs/modules/extra/textfilters/textfilters.js Cannot read property '1' of undefined","time":"2016-05-13T10:06:53.474Z","v":0}
{"name":"iris","hostname":"Pau1ms-MacBook-Pro.local","pid":4024,"level":50,"msg":"Error when calling hook hook_form_submit__textfilter from textfilters on line 207 of /Users/p/Documents/webs/in-house/iris-test1/node_modules/irisjs/utils.js Cannot read property 'replace' of undefined","time":"2016-05-13T10:09:03.196Z","v":0}
```

**Comment by FilipNest** [comment]
This should be fixed after https://github.com/CityWebConsultants/Iris/pull/227
