### ISSUE TITLE
Blank page on password reset page /user/password

### ISSUE THREAD

**Issue by pau1m** [CityWebConsultants/Iris#243]
<img width="1120" alt="screen shot 2016-05-13 at 11 33 06" src="https://cloud.githubusercontent.com/assets/431223/15245475/9908e736-18fe-11e6-9bf3-80ac03704e30.png">

Can't see anything in logs

**Comment by adam-clarey** [comment]
fixed in https://github.com/CityWebConsultants/Iris/pull/254
