### ISSUE TITLE
New 'Tags' field not visible on page create

### ISSUE THREAD

**Issue by pau1m** [CityWebConsultants/Iris#244]
As Admin, I added a field called Tags of type Tags to the Page type.
When I create a new page, the field is not visible and there is no button submit. After deleting the Tags field. The submit button displays normally.

<img width="1439" alt="screen shot 2016-05-13 at 11 40 46" src="https://cloud.githubusercontent.com/assets/431223/15245693/010bfd9a-1900-11e6-883a-f4efb3ea0831.png">
<img width="1222" alt="screen shot 2016-05-13 at 11 43 46" src="https://cloud.githubusercontent.com/assets/431223/15245692/010ae40a-1900-11e6-8fc1-f79404aae944.png">

``````
{"name":"iris","hostname":"Pau1ms-MacBook-Pro.local","pid":4325,"level":50,"msg":"Error when calling hook hook_form_render__field_settings__tags from tags on line 11 of /Users/p/Documents/webs/in-house/451-wtf/node_modules/irisjs/modules/extra/tags/tags.js Cannot set property 'settings' of undefined","time":"2016-05-13T10:40:15.218Z","v":0}
{"name":"iris","hostname":"Pau1ms-MacBook-Pro.local","pid":4325,"level":50,"msg":"No field type hook for: Tags","time":"2016-05-13T10:40:15.219Z","v":0}
{"name":"iris","hostname":"Pau1ms-MacBook-Pro.local","pid":4325,"level":50,"msg":"Error when calling hook hook_entity_field_fieldType_form__tags from tags on line 55 of /Users/p/Documents/webs/in-house/451-wtf/node_modules/irisjs/modules/extra/tags/tags.js Cannot read property 'tags' of undefined","time":"2016-05-13T10:40:38.256Z","v":0}
{"name":"iris","hostname":"Pau1ms-MacBook-Pro.local","pid":4325,"level":50,"msg":"Failed to load entity edit form. Hook error","time":"2016-05-13T10:40:38.257Z","v":0}```
``````

**Comment by FilipNest** [comment]
I know exactly where this bug is. Well spotted, thank you. 

```
{"name":"iris","hostname":"Pau1ms-MacBook-Pro.local","pid":4325,"level":50,"msg":"No field type hook for: Tags","time":"2016-05-13T10:40:15.219Z","v":0}
```

Is the key. It needs that hook to be defined in the tags module or needs to not demand it in entity_ui.js

**Comment by adam-clarey** [comment]
are you taking this one fil?

**Comment by FilipNest** [comment]
This was actually a lot simpler than the hook issue above. The settings definition had a `data = {}` which was wiping the form data and not showing the settings for properly. Works now (once pull request merged).
