### ISSUE TITLE
Nothing happens on autopath submit

### ISSUE THREAD

**Issue by pau1m** [CityWebConsultants/Iris#252]
Contents of single field stored but nothing else happens. Not sure what I should be seeing

<img width="1121" alt="screen shot 2016-05-13 at 13 08 04" src="https://cloud.githubusercontent.com/assets/431223/15247404/e5c6d918-190b-11e6-9a69-f3ae64926729.png">

**Comment by FilipNest** [comment]
I've added an updated message so people know their settings have changed. Also fixed an issue with the leading slash autofill while I was there. Tested the module and it seemed to work as intended.
