### ISSUE TITLE
Rewrite Folder Structure page in docs 

### ISSUE THREAD

**Issue by pau1m** [CityWebConsultants/Iris#255]
https://github.com/CityWebConsultants/Iris/wiki/Folder-structure

I've been editing little bits and bobs but writing up a ticket for this one because it's a wee bit more involved and I'll forget if I don't post it.

**Comment by FilipNest** [comment]
Done and split into two sections. One for core and one for people's sites. Feel free to add more explanation but this at least brings it up to date.
