### ISSUE TITLE
Add styling and behaviour for dropdown checkboxes field. Required for project

### ISSUE THREAD

**Issue by adam-clarey** [CityWebConsultants/Iris#34]

**Comment by FilipNest** [comment]
This shouldn't be in iris_core.js . Also the $ would break pages where jQuery is not included as aside from the form system iris doesn't need jQuery. 

If this is essential I'd recommend extending JSON form using iris.modules.forms.globals.registerWidget as documented over in https://github.com/CityWebConsultants/Iris/wiki/Form-system#extending-json-form-with-custom-fields
