### ISSUE TITLE
Add in optional handlebars helper library for common functions

### ISSUE THREAD

**Issue by facascante** [CityWebConsultants/Iris#99]
```

  Handlebars.registerHelper('compare', function (lvalue, operator, rvalue, options) {
    if (arguments.length < 4) {
      throw new Error("Handlerbars Helper 'compare' needs 3 parameters");
    }

    var result = eval("'" + lvalue + "' " + operator + " '" + rvalue + "'");
    if (result) {
      return options.fn(this);
    } else {
      return options.inverse(this);
    }
  });
```

**Comment by FilipNest** [comment]
Is it worth putting something like https://github.com/elving/swag in? It's loads of Handlebars helpers.

**Comment by facascante** [comment]
yeah this is better. those function are just generic utility that is a must have of server side template.
can we add?

**Comment by FilipNest** [comment]
How about an Iris module called handlebars_swag or something like that that adds this in the extra folder for now?

**Comment by facascante** [comment]
thats fine. i need equal helper :)

**Comment by FilipNest** [comment]
Going to do this as a contrib module as that leaves it up to the user. Can close this or wait until done.
